[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dps-common-python"
version = "0.1.0"
description = "Common shared modules for NLNZ Digital Preservation Python services"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
  { name = "National Library of New Zealand" }
]
dependencies = [
  "falcon>=3.0.0",
  "requests>=2.0.0",
  "xmltodict>=1.0.4",
  "azure-identity>=1.26.0",
  "azure-storage-queue>=12.18.0",
  "azure-storage-blob>=12.0.0",
  "azure-data-tables>=12.7.0"
]

[project.urls]
Homepage = "https://github.com/NLNZDigitalPreservation/dps-common-python"
Repository = "https://github.com/NLNZDigitalPreservation/dps-common-python"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["common", "common.*", "viridian", "viridian.*"]
